module elasticGreens2D

export aki_richards_line_force_2d

"""Linear interpolation with zero continuation outside a sampled interval."""
@inline function _sample_zero(values, t0, dt, time)
    position = (time - t0) / dt + 1
    (position < 1 || position > length(values)) && return 0.0
    lower = clamp(floor(Int, position), 1, length(values))
    lower == length(values) && return Float64(values[end])
    fraction = position - lower
    return muladd(fraction, values[lower + 1] - values[lower], values[lower])
end

function _cumulative_moments(source, t0, dt)
    n = length(source)
    zeroth = zeros(Float64, n)
    first = zeros(Float64, n)
    for index in 2:n
        ta = t0 + (index - 2) * dt
        tb = ta + dt
        fa, fb = Float64(source[index - 1]), Float64(source[index])
        zeroth[index] = zeroth[index - 1] + dt * (fa + fb) / 2
        first[index] = first[index - 1] + dt * (ta * fa + tb * fb) / 2
    end
    return zeroth, first
end

"""
    aki_richards_line_force_2d(times, receivers; source, vp, vs, rho,
        force_time_function, force_amplitude=1, component=:z, ...)

Full-space isotropic 2-D displacement and velocity generated by a line force.
The implementation evaluates the point-force Green tensor (near-, P- and
S-field terms in the Aki--Richards convention) and integrates it along the
out-of-plane direction. Consequently its force unit is N/m, matching the 2-D
FD, OPT and SPECFEM experiments.

The returned arrays have layout `(time, receiver, component)` with components
`(:x, :z)`. This is a numerical evaluation of an analytical Green tensor; the
`out_of_plane_step` convergence should be checked by halving it.
"""
function aki_richards_line_force_2d(
    times::AbstractVector{<:Real},
    receivers;
    source,
    vp::Real,
    vs::Real,
    rho::Real,
    force_time_function,
    force_amplitude::Real=1.0,
    component::Symbol=:z,
    out_of_plane_step::Real=250.0,
    source_tail_periods::Real=6.0,
    source_frequency::Real,
)
    component === :z || throw(ArgumentError(
        "the current benchmark implementation supports a vertical line force",
    ))
    t = Float64.(collect(times))
    length(t) >= 3 || throw(ArgumentError("at least three times are required"))
    all(diff(t) .> 0) || throw(ArgumentError("times must increase"))
    dt = minimum(diff(t)) / 4
    margin = source_tail_periods / Float64(source_frequency)
    table_t0 = first(t) - margin - maximum(t)
    table_t1 = last(t) + margin
    table_times = collect(table_t0:dt:table_t1)
    force = Float64(force_amplitude) .* force_time_function.(table_times)
    moment0, moment1 = _cumulative_moments(force, table_t0, dt)

    sample_force(time) = _sample_zero(force, table_t0, dt, time)
    sample_moment(values, time) = _sample_zero(values, table_t0, dt, time)
    function near_integral(time, lower, upper)
        upper <= lower && return 0.0
        a, b = time - upper, time - lower
        f0 = sample_moment(moment0, b) - sample_moment(moment0, a)
        f1 = sample_moment(moment1, b) - sample_moment(moment1, a)
        return time * f0 - f1
    end

    receiver_list = collect(receivers)
    displacement = zeros(Float64, length(t), length(receiver_list), 2)
    max_distance = Float64(vp) * (last(t) - table_t0)
    dy = Float64(out_of_plane_step)
    y_values = collect(0.0:dy:max_distance)
    prefactor = inv(4π * Float64(rho))

    for (receiver_index, receiver) in enumerate(receiver_list)
        dx = Float64(receiver.x - source.x)
        dz = Float64(receiver.z - source.z)
        hypot(dx, dz) > 0 || throw(ArgumentError(
            "the analytical receiver cannot coincide with the source",
        ))
        for (iy, y) in enumerate(y_values)
            weight = (iy == 1 || iy == length(y_values)) ? dy : 2dy
            # Symmetric integration over negative and positive out-of-plane y.
            R = sqrt(dx^2 + y^2 + dz^2)
            gamma_x, gamma_z = dx / R, dz / R
            p_delay, s_delay = R / vp, R / vs
            for (time_index, time) in enumerate(t)
                near = near_integral(time, p_delay, s_delay) / R^3
                p = sample_force(time - p_delay) / (vp^2 * R)
                s = sample_force(time - s_delay) / (vs^2 * R)
                # j=z. Only the in-plane i=x,z components survive symmetry.
                displacement[time_index, receiver_index, 1] += weight * prefactor * (
                    3gamma_x * gamma_z * near + gamma_x * gamma_z * (p - s))
                displacement[time_index, receiver_index, 2] += weight * prefactor * (
                    (3gamma_z^2 - 1) * near + gamma_z^2 * p +
                    (1 - gamma_z^2) * s)
            end
        end
    end

    velocity_times = (t[1:end-1] .+ t[2:end]) ./ 2
    velocity = diff(displacement; dims=1) ./ reshape(diff(t), :, 1, 1)
    return (
        time=t,
        displacement=displacement,
        velocity_time=velocity_times,
        velocity=velocity,
        components=(:x, :z),
        convention=:aki_richards_point_force_integrated_to_2d_line_force,
        out_of_plane_step=dy,
        units=(displacement=:m, velocity=:m_per_s, force=:N_per_m),
    )
end

end
